### ISSUE TITLE
AFK Players

### ISSUE THREAD

**Issue by t0mtee** [Sirmentio/fabric-mod-ihgm#2]
I have a feature request:

- There is only one player online
- This player goes AFK after no movement in a period of time (let's say 5 minutes)
- When they go AFK, the time is recorded.
- Time is allowed to progress
- When they exit AFK or another player joins, time reverts to the recorded time.

This would be useful for farms as stopping daylight cycle could disrupt them but it would also allow a good measure of how long the server has been up for

**Comment by HunnyBon** [comment]
I'm not so sure if that fits the scope of the project. The idea is moreso for servers that require time to stop when no one's online, not to make farms easier. If I implemented AFK players, I would definitely pause tickrate.
